### ISSUE TITLE
No option to specify proxies in the get request.

### ISSUE THREAD

**Issue by KateRooney** [therealexpertai/nlapi-python#14]
We are trying to access the api from behind a corporate proxy. We are receiving timeout errors. We'd like to set the proxy in and the cert in the get request but cannot see the syntax to do that. We can do the same from curl on a terminal and that is successful.

**Comment by avarone-github** [comment]
Hi Kate, we are looking at your request. More on this soon.

**Comment by avarone-github** [comment]
Kate, here I am.  
Since `expertai-nlapi` Python client for Natural Language API uses the `requests` library, you can specify the proxy by setting the `HTTPS_PROXY` environment variable, as indicated [here](https://2.python-requests.org/en/master/user/advanced/#proxies).  
Please try and let me know if it works in your case.

**Comment by avarone-github** [comment]
I'm closing the issue since setting the environment variable seems to be the solution and I got no feedback from @KateRooney.
