### ISSUE TITLE
HTTP Error 429 

### ISSUE THREAD

**Issue by Hilal-Urun** [therealexpertai/nlapi-python#17]
Hi, I'm trying to do threading but when I send request for 20 papers I'm getting Too Many Requests Error. I'm not using the free version of api. Is there any solution for that? 
Thank you  🙏

**Comment by Hilal-Urun** [comment]
Okey, I'm going to try it, thank you so much

**Comment by zlatev** [comment]
Hello @Hilal-Urun,

Have you got any news after your next attempts?

Meanwhile, we had tried to replicate your problem, but without success. We had tested calling full_analysis method with 20 and more threads, with different input texts and didn't receive error 429.

If you still experience this problem, please give us more details, e.g.: specific method you are calling, text examples or an actual code example of yours.

Thank you.

**Comment by zlatev** [comment]
Hello @Hilal-Urun,

How have you fixed the original problem? 

Regarding your new problem, could you give us more details? Could you please provide us with your code, so that we can use it to replicate the issue at our side? Also, details like size of texts, types of analysis, etc. will be very useful for us to understand what exactly is the problem.

**Comment by avarone-github** [comment]
Hi @Hilal-Urun, I'm closing this issue due to lack of feedback.
